openapi: 3.0.3
info:
  title: QC external balance API
  version: '1.0'
servers: []
paths:
  /v1/b2b-gateway/customers:
    post:
      summary: Create a new customer.
      description: Register a new customer.
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - customer_id
                - country_code
                - ip
                - email
              properties:
                customer_id:
                  type: string
                  description: B2B client customer's ID.
                country_code:
                  type: string
                  description: B2B client customer's country ISO 3166 alpha-2 code.
                ip:
                  type: string
                  description: B2B client customer's IP address.
                email:
                  type: string
                  description: B2B client customer's email.
                phone_number:
                  type: string
                  description: B2B client customer's phone number.
                account_timezone:
                  type: string
                  description: B2B client customer's account timezone.
                first_name:
                  type: string
                  description: B2B client customer's first name.
                middle_name:
                  type: string
                  description: B2B client customer's middle name.
                last_name:
                  type: string
                  description: B2B client customer's last name.
                date_of_birth:
                  type: string
                  format: date
                  description: B2B client customer's birthday.
      responses:
        '201':
          description: The customer's account has been created.
        '400':
          description: The request payload is not valid.
        '401':
          description: Unauthorized. JWT token is not present or is not valid.
        '403':
          description: Access to server is forbidden.
        '409':
          description: The customer already exists.
        '422':
          description: Unprocessable entity.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostCustomersUnprocessableResponseEntityContent'
        '429':
          description: Too many requests.
        '451':
          description: The customer is not allowed access.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerIsNotAllowedAccessResponseContent'
              examples:
                customer_country_restriction:
                  value:
                    error: customer_country_restriction
                    message: The customer's current country is not allowed.
                customer_currency_restriction:
                  value:
                    error: customer_currency_restriction
                    message: The customer's balance currency is not allowed.
        '500':
          description: Internal server error.
  '/v1/b2b-gateway/customers/{customer_id}/block':
    parameters:
      - schema:
          type: string
        name: customer_id
        in: path
        required: true
    post:
      summary: Block customer's account.
      description: Disable customer's account.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: The customer is disabled successfully.
        '401':
          description: Unauthorized. JWT token is not present or is not valid.
        '403':
          description: Access to server is forbidden.
        '404':
          description: The customer is not found.
        '500':
          description: Internal server error.
  '/v1/b2b-gateway/customers/{customer_id}/session':
    parameters:
      - schema:
          type: string
        name: customer_id
        in: path
        required: true
    post:
      summary: Create onetime login URL.
      description: Creates user's session and returns onetime login URL for HTML iframe located on the client's site.
      security:
        - bearerAuth: []
      requestBody:
        description: Payload to build URL for HTML iframe.
        content:
          application/json:
            schema:
              type: object
              required:
                - balance_id
                - balance_currency_code
                - country_code
                - ip
                - locale
                - site_domain
              properties:
                balance_id:
                  type: string
                  description: The customer's balance ID.
                balance_currency_code:
                  type: string
                  description: The customer's balance currency code.
                country_code:
                  type: string
                  description: Country ISO 3166 alpha-2 code detected by customer's IP address.
                ip:
                  type: string
                  description: The customer's IP address.
                locale:
                  type: string
                  description: Locale name (like en_US or ru_RU). If locale is not supported by QC system, then will be used fallback locale.
                site_domain:
                  type: string
                  description: Site/mirror domain for iframe URL.
                  example: trade.brand-domain.com
      responses:
        '201':
          description: URL created.
          content:
            application/json:
              schema:
                type: object
                required:
                  - url
                properties:
                  url:
                    type: string
                    description: The URL for HTML iframe located on the client's site.
        '400':
          description: The request payload is not valid.
        '401':
          description: Unauthorized.
        '403':
          description: Access to server is forbidden.
        '404':
          description: The customer is not found.
        '409':
          description: The customer's balance ID mismatches with balance currency code.
        '422':
          description: Unprocessable entity.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostCustomersSessionUnprocessableResponseEntityContent'
        '429':
          description: Too many requests.
        '451':
          description: The customer is not allowed access.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerIsNotAllowedAccessResponseContent'
              examples:
                customer_country_restriction:
                  value:
                    error: customer_country_restriction
                    message: The customer's current country is not allowed.
                customer_currency_restriction:
                  value:
                    error: customer_currency_restriction
                    message: The customer's balance currency is not allowed.
        '500':
          description: Internal server error.
  '/v1/b2b-gateway/allowed-countries':
    get:
      summary: Get countries allowed to access.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Countries allowed to access.
          content:
            application/json:
              schema:
                type: object
                required:
                  - countries
                properties:
                  countries:
                    type: array
                    description: Allowed countries.
                    items:
                      $ref: '#/components/schemas/Country'
        '401':
          description: Unauthorized.
        '403':
          description: Access to server is forbidden.
        '500':
          description: Internal server error.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    PostCustomersUnprocessableResponseEntityContent:
      type: object
      properties:
        customer_id:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: string
              enum:
                - is_required
            message:
              type: string
        country_code:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: string
              enum:
                - is_required
                - unknown_country_code
            message:
              type: string
        ip:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: string
              enum:
                - is_required
                - invalid_ip_format
            message:
              type: string
        email:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: string
              enum:
                - is_required
                - invalid_email_format
            message:
              type: string
    PostCustomersSessionUnprocessableResponseEntityContent:
      type: object
      properties:
        balance_id:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: string
              enum:
                - is_required
            message:
              type: string
        balance_currency_code:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: string
              enum:
                - is_required
            message:
              type: string
        country_code:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: string
              enum:
                - is_required
                - unknown_country_code
            message:
              type: string
        ip:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: string
              enum:
                - is_required
                - invalid_ip_format
            message:
              type: string
        locale:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: string
              enum:
                - is_required
            message:
              type: string
        site_domain:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: string
              enum:
                - is_required
            message:
              type: string
    CustomerIsNotAllowedAccessResponseContent:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code.
          enum:
            - customer_country_restriction
            - customer_currency_restriction
        message:
          type: string
          description: Human readable error description.
    Country:
      type: object
      required:
        - name
        - short_code
        - iso_code
      properties:
        name:
          type: string
          description: Human readable country name.
        short_code:
          type: string
          description: Two symbols country ISO 3166 alpha-2 code.
        iso_code:
          type: string
          description: Three symbols country ISO 3166 alpha-3 code.
